version: '3.7'
services:


  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    build: ./dockerfiles
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./config/airflow.cfg:/opt/local/airflow/airflow.cfg
      - ./config:/opt/airflow
      - ./requirements.txt:/requirements.txt
      - ./data.csv:/data.csv
    ports:
      - "8080:8080"
    command: webserver